### ISSUE TITLE
[Bug]: `tcrw` doesn't work out of the box on NixOS

### ISSUE THREAD

**Issue by pinage404** [murex/TCR#333]
### Describe the bug

When i run this command

```sh
./tcrw solo
```

I get theses errors

```txt
[TCR] Downloading tcr_0.25.0_Linux_x86_64.tar.gz
[TCR] Downloading v0.25.0.tar.gz
mv: cannot stat '/Kata-Slow-Code/tcr/tcr_go/download/tcr-0.25.0/doc': No such file or directory
/Kata-Slow-Code/javascript/../tcr/tcr_go/tcr_go.sh: line 235: /Kata-Slow-Code/tcr/tcr_go/bin/tcr_Linux_x86_64: No such file or directory
```

### To Reproduce

1. Install [NixOS](https://nixos.org/download.html) OR start a NixOS container : `docker run --interactive --tty --rm nixos/nix:2.15.1`
2. "Install" `git` for the current shell : `nix-shell --packages git`
3. Clone the repo : `git clone https://github.com/philou/Kata-Slow-Code`
4. Go to this repo : `cd Kata-Slow-Code/`
5. Go to one language subfolder : `cd ./javascript/`
6. Make `tcrw` executable : `chmod +x tcrw`
7. Execute `tcrw` : `./tcrw solo` 
8. Watch the following error
```txt
[TCR] Downloading tcr_0.25.0_Linux_x86_64.tar.gz
[TCR] Downloading v0.25.0.tar.gz
mv: cannot stat '/Kata-Slow-Code/tcr/tcr_go/download/tcr-0.25.0/doc': No such file or directory
/Kata-Slow-Code/javascript/../tcr/tcr_go/tcr_go.sh: line 235: /Kata-Slow-Code/tcr/tcr_go/bin/tcr_Linux_x86_64: No such file or directory
```

### Expected behavior

I expected to have one of this : 
* a binary compiled with all needed dependencies (without dynamic libraries)
* a README that list which dynamic libraries should be installed
* `flake.nix` that packages the binary with Nix (and can handle the development environment needed)

### Working Environment

1. OS: [NixOS](https://nixos.org) `22.11.20230520.7dc71ae (Raccoon) x86_64`
2. Version: `tcr version 0.25.0`

### Additional Context

NixOS is a Linux distribution made to be highly reproducible : everything is declarative, versionnable

Others Linux distributions install specific version of libraries globally on specific paths

> Binaries normally do not work out of the box when you download them because they normally just assume that libraries can be found in hardcoded paths such as `/lib`. However this assumption is incorrect on NixOS systems due to the inner workings of `nix` - there is no default path, everything gets set to the corresponding version on compile time. 
https://nixos.wiki/wiki/FAQ#I.27ve_downloaded_a_binary.2C_but_I_can.27t_run_it.2C_what_can_I_do.3F

As a workaround, i can use [`steam-run`](https://search.nixos.org/packages?type=packages&query=steam-run)

```sh
NIXPKGS_ALLOW_UNFREE=1 nix-shell --packages steam-run
steam-run ./tcrw solo
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mengdaming** [comment]
Hello @pinage404 

Thank you for reporting this issue. We never tried TCR with NixOS before, so it's a nice opportunity for us to extend our list of supported platforms!

I've prepared a fix that I was able to run successfully in a replit.com nixos shell, but before merging the changes I would like to confirm with you that everything is fixed from your point of view, if you don't mind spending a bit of time testing it of course :)

Here's how you can test it (this is an update from the steps you provided above. Main changes are in step 5 and 7)

1. Install [NixOS](https://nixos.org/download.html) OR start a NixOS container : `docker run --interactive --tty --rm nixos/nix:2.15.1`
2. "Install" git for the current shell : `nix-shell --packages git`
3. Clone the repo : `git clone https://github.com/philou/Kata-Slow-Code`
4. Go to this repo : `cd Kata-Slow-Code/`
5. Checkout the branch containing the fix: `git checkout origin/bugfix/nixos`
6. Go to one language subfolder : `cd ./javascript/`


7. Check that tcr can be started: `./tcrw info`


8. Expected outcome:


```stacktrace
[TCR] Downloading tcr_0.25.2_Linux_x86_64.tar.gz
[TCR] Downloading v0.25.2.tar.gz
[TCR] Loading configuration: /home/runner/nix-and-tcr/Kata-Slow-Code/javascript/.tcr/config.yml
[TCR] Loading toolchains configuration
[TCR] Loading languages configuration
- Version:  0.25.2
- OS Family:    linux
- Architecture: amd64
- Commit:   76029b6588d54dea053b0a7014fed53930aebec9
- Build Date:   2023-05-30T15:36:39Z
- Built By: goreleaser
```

Thank you again. Let me know if anything is unclear or missing.

**Comment by pinage404** [comment]
Yeah ! It works

```txt
./tcrw info
[TCR] Downloading tcr_0.25.2_Linux_x86_64.tar.gz
[TCR] Downloading v0.25.2.tar.gz
[TCR] Loading configuration: /Kata-Slow-Code/javascript/.tcr/config.yml
[TCR] Loading toolchains configuration
[TCR] Loading languages configuration
- Version:      0.25.2
- OS Family:    linux
- Architecture: amd64
- Commit:       76029b6588d54dea053b0a7014fed53930aebec9
- Build Date:   2023-05-30T15:36:39Z
- Built By:     goreleaser
```

```txt
./tcrw solo
[TCR] Loading configuration: /Kata-Slow-Code/javascript/.tcr/config.yml
[TCR] Loading toolchains configuration
[TCR] Loading languages configuration
[TCR] Starting TCR version 0.25.2...
[TCR] Base directory is /Kata-Slow-Code/javascript
[TCR] Work directory is /Kata-Slow-Code/javascript
[TCR] Test-breaking changes will not be committed
[TCR] ─────────────────────────────────────────────────────────────────────────
[TCR] Running in solo mode
[TCR] ─────────────────────────────────────────────────────────────────────────
[TCR] Base Directory: /Kata-Slow-Code/javascript
[TCR] Work Directory: /Kata-Slow-Code/javascript
[TCR] Language=javascript, Toolchain=yarn
[TCR] Running on git branch "HEAD" with auto-push disabled
[TCR] ─────────────────────────────────────────────────────────────────────────
[TCR] Starting with Driver role. Press ? for options
[TCR] Working locally on branch HEAD
[TCR] Going to sleep until something interesting happens
- watching /Kata-Slow-Code/javascript/src
- watching /Kata-Slow-Code/javascript/test
```

Thanks for the fast answer
