### ISSUE TITLE
[Feature]: Remove tcr_shell from the setup files

### ISSUE THREAD

**Issue by philou** [murex/TCR#415]
### Contact Details

philippe.bourgau@gmail.com

### Feature Request

The tcr_shell variant is now useless and adds clutter to the installation files

### Feature Description

- Remove the tcr_shell from the install dir
- Simplify the scripts and directory structure accordingly

### Alternatives

Actively maintain the tcr_shell for a good reason (don't know any)

### Additional Context

The sample repo I was working on is https://github.com/lynchjames/note-refactor-obsidian. Here is a commit I made to setup TCR: https://github.com/philou/note-refactor-obsidian/commit/c75e490bea5bcb5eb54c9ea062ced0b3ee6aed71

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mengdaming** [comment]
Actually there's nothing related to tcr_shell in TCR repo on GitHub (tcr_shell is only in our kata repos). I guess we'd rather manage this directly as a jira ticket

**Comment by mengdaming** [comment]
tcr_shell is now removed from all our kata repos.
