### ISSUE TITLE
[Bug]: TCR Freezing when python code gets into an infinite loop

### ISSUE THREAD

**Issue by philou** [murex/TCR#694]
### Describe the bug

Whenever the python code gets into an infinite loop in the test, TCR stays there and we have no choice but to kill and restart it.

### To Reproduce

1. Use the python example
2. Start TCR
3. add an infinite `while` loop in a test
4. Save and see TCR freezing

### Expected behavior

I would expect that TCR would kill the tests after a timeout period

### Working Environment

1. OS: windows
3. Version [e.g. 1.0.0]

### Additional Context

Additional information

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mengdaming** [comment]
I confirm that this behaviour can be observed with any language/toolchain as soon as there is an infinite loop somewhere while the tests are running
